language: php

services:
  - mysql

php:
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - REPO_NAME=cakephp-queue
    - PLUGIN_NAME=Queue
    - REQUIRE=""
    - DB=mysql CAKE_VERSION=2

    - secure: "lMvqukdTy45r8VXnIaIKUI7i39dwDQ7u7yPeN019TVZDhYGa3ul9S0PxWYTXvyay+PqnEtCcp/dfwo57pLDfFKOnD6omLZiwFU4F10P8TIm6cnokw/4dnFEsZnK8fuvqDduwrSZwyTk9J1fvOYSOcGkOOm7y5AqSaDYEpQIPtuI="

  matrix:
    - CAKE_VERSION=2.9
    - CAKE_VERSION=2.10 PHPUNIT_VERSION=^5.7

matrix:
  include:
    - php: 7.1
      env:
        - CODECOVERAGE=1 PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - PHPCS=1
    - php: 7.1
      env:
        - FOC_VALIDATE=1
  exclude:
    - php: 7.2
      env: CAKE_VERSION=2.9

branches:
  only:
    - master
    - 2.x

before_script:
  - git clone -b master https://github.com/Oefenweb/travis --depth 1 ../travis
  - travis_wait ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
  slack:
    rooms:
      secure: "UH0zEV8YgA/cDCxXRoym6/zTYwy7YC1yiAxAYgancnaOFbi3Gsn3IoD9yYr+SNMdl0QnLFRIPxEUH+YCM8EL9Q1233fTf+x27LtSPTiCpjppmdFlrxt5AxKP6kw4Q2eKNO+YXywwUyK+KuuhYC+xLo7h6cA9DIGy14CilK5DeEM="
